add pipeline

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,9 +1,6 @@
 name: Run Tests
 
-on:
-  push:
-    branches:
-      - main
+on: pull_request
 
 jobs:
   test:
@@ -16,7 +13,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '14'
+          node-version: '20'
 
       - name: Install dependencies
         run: npm install
@@ -27,10 +24,15 @@ jobs:
       - name: Check coverage
         run: |
           COVERAGE_THRESHOLD=90
-          COVERAGE=$(grep "Statements" coverage/lcov-report/index.html | grep -oP "\d+(?=%)")
-          if [ "$COVERAGE" -lt "$COVERAGE_THRESHOLD" ]; then
-            echo "Test coverage is below threshold. Exiting with failure."
-            exit 1
+          if [ -f "coverage/lcov-report/index.html" ]; then
+            COVERAGE=$(grep "Statements" coverage/lcov-report/index.html | grep -oP "\d+(?=%)")
+            if [ "$COVERAGE" -lt "$COVERAGE_THRESHOLD" ]; then
+              echo "Test coverage is below threshold. Exiting with failure."
+              exit 1
+            else
+              echo "Test coverage meets threshold. Proceeding."
+            fi
           else
-            echo "Test coverage meets threshold. Proceeding."
+            echo "Coverage report not found. Exiting with failure."
+            exit 1
           fi
